version: '3.8'

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
                - DATABASE_URL=${DATABASE_URL}
                - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
                - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        environment:
            - NODE_ENV=production
        restart: always
        ports:
            - 3000:3000