import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';
import '@/styles/globals.css';
import  Provider  from '@/components/Provider';
import type { Metadata } from 'next';
import { Prompt } from 'next/font/google';

const prompt = Prompt({ subsets: ["latin"],weight: "400" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={prompt.className}>
        <Provider>
        <main className="">
        {/* <main className='h-screen flex flex-col justify-center items-center'> */}
          <Navbar />
          {children}
        </main>
        <Toaster />
        </Provider>
       
      </body>
    </html>
  );
}
